### ISSUE TITLE
Prepare prototype for expanding MiniRyś robot model with servomotor-based grabbing mechanism

### ISSUE THREAD

**Issue by Dangield** [GroupOfRobots/RobotMechanics#7]

**Comment by Dangield** [comment]
- [ ] Push recent changes
- [ ] Print new versions of parts

**Comment by gosidul** [comment]
Added improved parts' models, stl files are in folder solid_v5/stl_do_druku on the TwitchGo branch. Grabber arms and the servo holder lid need to have screw nuts embedded in them. One of the gears needs to be printed twice, which is mentioned in the file name.
